# Generated by Django 3.1.7 on 2021-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='poll_name',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_choice',
            field=models.CharField(default='Enter value', max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('CHOICE', 'CHOICE'), ('MULTIPLE', 'MULTIPLE')], default='TEXT', max_length=8),
        ),
    ]
