# Generated by Django 3.1.7 on 2021-04-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210402_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
