# Generated by Django 3.1.7 on 2021-04-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_answer_type_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='type_question',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Enter value', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.choice'),
            preserve_default=False,
        ),
    ]
